### ISSUE TITLE
Can openTVtoXML take a stream from a remote host?

### ISSUE THREAD

**Issue by FlexMcMurphy** [dave-p/openTVtoXML#2]
In the ReadMe, usage for openTVtoXML is:
```
cd /opt/openTVtoXML
./openTVtoXML -f -s
```
My satellite tuners are on one machine, a ZgemmaH7S running enigma2/OpenATV and minisatip. This feeds satellite channels to TVHeadend on a separate machine: Ubuntu Server on a Pi 4. The Zgemma is a minimal Linux OS and I cannot install or compile openTVtoXML on it. I compiled it on the Pi 4 but it doesn't see the stream on the ZGemma.

Is it possible to run openTVtoXML on my Pi 4 and direct it to the device in the /dev/dvb/adapter0 directory on the remote Zgemma? Its on the same LAN.

Could openTVtoXML accept a recording of the EPG channel on the OpenTV Sky UK transponder? A recording in .ts or a.mpeg format for instance?

Alternatively would you happen to know if there is a way to send the stream from the Zgemma to a device on the Pi 4 that openTVtoXML will listen in on? Not sure if that is possible.

Cheers,

Flex

**Comment by dave-p** [comment]
openTVtoXML uses the tuner hardware to filter the data stream and to present it in discrete packets. While it is possible to do all this in software, it would be a far from trivial task. Sorry.
